# docker-compose.yml
# Copyright (C) 2018 shady <shady@MrRobot.local>
#
version: "3"
services:
  mysql:
    build: ./deployment/mysql
    image: shadybat/seckill-mysql:v1.1
    environment:
      MYSQL_ROOT_PASSWORD: ${SECKILL_DB_PASSWORD}
      MYSQL_DATABASE: ${SECKILL_DB_NAME}
    volumes:
      - ${DOCKER_DIR}/volumes/data:/var/lib/mysql # mysql data source
      - ${DOCKER_DIR}/volumes/log:/var/log/mysql # mysql log
    networks:
      - seckill

  redis:
    build: ./deployment/redis
    image: shadybat/seckill-redis:v1.1

  django:
    image: shadybat/seckill-django:v1.1
    build:
      context: ./
      dockerfile: ./deployment/django/Dockerfile
    depends_on:
      - redis
      - mysql
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
      SECKILL_DEBUG: ${SECKILL_DEBUG}
      SECKILL_SECRET_KEY: ${SECKILL_SECRET_KEY}
      SECKILL_DB_HOST: mysql
      SECKILL_DB_PORT: 3306
      SECKILL_DB_USERNAME: ${SECKILL_DB_USERNAME}
      SECKILL_DB_PASSWORD: ${SECKILL_DB_PASSWORD}
      SECKILL_DB_NAME: ${SECKILL_DB_NAME}
      SECKILL_SENTRY: ${SECKILL_SENTRY}
      SECKILL_ADMIN_NAME: ${SECKILL_ADMIN_NAME}
      SECKILL_ADMIN_EMAIL: ${SECKILL_ADMIN_EMAIL}
      SECKILL_ADMIN_PASS: ${SECKILL_ADMIN_PASS}
    # mount django static file, served by nginx
    volumes:
      - ${DOCKER_DIR}/volumes/statics:/env/app/collectstatic/statics
      - ${DOCKER_DIR}/volumes/media:/env/app/media
    networks:
      - seckill

  nginx:
    image: shadybat/seckill-nginx:v1.1
    build:
      context: ./
      dockerfile: deployment/nginx/Dockerfile
    depends_on:
      - django
    ports:
      - "1984:80"
    volumes:
      - ${DOCKER_DIR}/volumes/statics:/usr/share/nginx/statics
      - ${DOCKER_DIR}/volumes/media:/usr/share/nginx/media
    networks:
      - seckill

networks:
  seckill:
