# Generated by Django 2.2.4 on 2019-08-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("seckill", "0002_auto_20190810_0719")]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="sart_time", new_name="start_time"
        )
    ]
