# Generated by Django 2.2.4 on 2019-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("seckill", "0003_auto_20190810_1614")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=250),
        )
    ]
