# Generated by Django 2.2.4 on 2019-08-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("seckill", "0004_auto_20190810_1643")]

    operations = [
        migrations.AlterUniqueTogether(
            name="order", unique_together={("uuid", "product")}
        )
    ]
