# Generated by Django 2.2.4 on 2019-08-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("seckill", "0005_auto_20190810_1700")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="seckill.Product",
                verbose_name="product_id",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="seckill.Activity",
                verbose_name="activity_id",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="order", unique_together={("uuid", "activity")}
        ),
        migrations.RemoveField(model_name="order", name="product"),
    ]
